version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: recruiting_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recruiting_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recruiting_backend
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=5432
      - APP_ENV=development
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - recruiting_network
    volumes:
      - ./backend:/app
      - /app/vendor

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: recruiting_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - recruiting_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:


networks:
  recruiting_network:
    driver: bridge
